### ISSUE TITLE
Ps4 support

### ISSUE THREAD

**Issue by ZeteCx** [flint-gg/easyshare#13]
**Is your feature request related to a problem? Please describe.**
It's just added functionality on top of the great work this program already does. I'd just like to have it also for my ps4 which have the same problem. 

**Describe the solution you'd like**
Adding the option for the bot to also track #ps4share hash tag and work the same from them. 

**Describe alternatives you've considered**
Nothing really to add. 

**Additional context**
I really like the idea on general and I woukd love using it on my second console. 
Here's an example link to a photo I uploaded from my ps4 if you need it for whatever reason
https://twitter.com/originalname33/status/1305839316506218498?s=09

**Comment by T0TProduction** [comment]
Thanks for the Feedback!
We've already thought about that, but I don't play PS4 myself so we weren't sure if that's really a problem there. 
Im going to put this on the roadmap, but i don't know how quickly i'll get to it.

Changes we would need to make:
The main reason it doesn't work right now, even with the secondary hashtags, is that we verify if the tweet comes from a Nintendo Switch. We might need to add toggles for each console a user wants to use, and then allow all hashtags to work for all the chosen consoles.
And add the default PS4 hashtag like in your example.

**Comment by ZeteCx** [comment]
Yes, thank you for the fast respond.
Its the same problem in ps4, i mean you can create a second account and send then the file... then go and download it form your phone... yeah its not great
and yeah its like the #nintendoswitch hashtag - the #PS4share, it will always come form a ps4. it auto apply that hashtag and i dont think you can delete it either from the console.

**Comment by T0TProduction** [comment]
@ZeteCx as of now ps4 share is supported!
