### ISSUE TITLE
tweets not being tracked after long twitter connection time

### ISSUE THREAD

**Issue by T0TProduction** [flint-gg/easyshare#7]
**Describe the bug**
After some time the twitter stream did not send events anymore, making the service work as if offline.
Restarting the server fixed the issue, probably only temporarily.

**Expected behavior**
The service should always be online. *If* the stream really stops sending *any*  tweets, the server should renew the connection as it already does when the connection to the stream fails.

**Comment by T0TProduction** [comment]
this is an error that most likely killed the stream at some point, so maybe this is the reason it died last time too:
![image](https://user-images.githubusercontent.com/18548570/89464436-c3d44980-d770-11ea-8ffb-1723bfda95dd.png)

**Comment by T0TProduction** [comment]
idea: count tweets we got over 2 seconds intervals
if 2 intervals after each other are empty, we assume the stream died and restart
well need to test and see if this triggers too often in quiet times

**Comment by maybeanerd** [comment]
Seems to have been fixed on Twitters side. If it still occurs, we can reopen this issue.
